### ISSUE TITLE
Able to perform Reflected XSS on Routes

### ISSUE THREAD

**Issue by AshrefRaj** [tata1mg/catalyst-core#17]
### Screenshots:
[
<img width="576" alt="Screenshot 2024-12-12 at 13 54 31" src="https://github.com/user-attachments/assets/9683e10e-0eb0-4df9-8fed-913eefba5871" />
](url)

### Environment:
- **Version:** Affected till 0.0.1-beta.8

### Context:
We're able to execute scripts from the URL which falls under reflected xss category. This is a critical vulnerability and can lead to compromise of the entire application. Please fix this on priority.
Attached screenshot for reference.

---
**Priority:** High
---

**Comment by Uttkarsh-Srivastava** [comment]
Hey @AshrefRaj ,
Can you please help us with steps to reproduce this bug?

**Comment by AshrefRaj** [comment]
Yes @Uttkarsh-Srivastava 

### Example:
Craft a URL with script payload, such as:
```
http://xyz.com/patient/dashboardkdsh</script><script>alert(document.cookie)</script>
```

#### Result:
When the URL is accessed, the script is executed, leading to exposure of cookies and other sensitive data.

### Steps to Reproduce:
1. Open the application deployed at `xyz.com` which is built with catalyst.
2. Log in to the application to populate the cookies.
3. Navigate to the `/patient/dashboard` route.
4. Append the following payload to the route in the browser's address bar:
   ```
   kdsh</script><script>alert(document.cookie)</script>
   ```
   some random chars are added to make the router not match any path
5. Observe the execution of the injected script, which displays the document's cookies in an alert box.

**Comment by mayansharma** [comment]
Hello @AshrefRaj,
A new version of catalyst has been published that fixes this issue

Tag: https://github.com/tata1mg/catalyst-core/releases/tag/v0.0.1-beta.9
Package: https://www.npmjs.com/package/catalyst-core/v/0.0.1-beta.9
