### ISSUE TITLE
Environment variables are bundled with the app build

### ISSUE THREAD

**Issue by AshrefRaj** [tata1mg/catalyst-core#18]
We're able to see environment variables getting bundled together with the app.bundle.js.
These include confidential keys, environment build vars, fingerprints etc.

Affected Version: 

Observed from 0.0.1-beta.2
Till 0.0.1-beta.7

**Comment by Uttkarsh-Srivastava** [comment]
Hey @AshrefRaj 
This issue was fixed in [pull request](https://github.com/tata1mg/catalyst-core/pull/14)

**Comment by AshrefRaj** [comment]
Confirmed to have been fixed. 
No issues in beta.8.
Thanks!
